<img align="centre" src="../../Supplementary_data/Github_banner.jpg" width="100%">

# Enhanced Combined Drought Index - Precipitation Drought Index

* **Products used:** 
[rainfall_chirps_daily](https://explorer.digitalearth.africa/products/rainfall_chirps_daily)

## Background 

Drought is an extended period, during which, fresh water availability and accessibility for the ecosystem at a given time and place is below normal, due to unfavourable spatial and temporal distribution of rainfall, temperature, soil moisture and wind characteristics [(Balint et al., 2013)](https://doi.org/10.1016/B978-0-444-59559-1.00023-2). Severe droughts can affect large populations, leading to a long-term threat to people’s livelihoods and result in tremendous economic loss [(Enenkel et al., 2016)](https://doi.org/10.3390/rs8040340).

The **Enhanced Drought Index** is a combination of the following components: Vegetation, Precipitation, Temperature and Soil moisture.

This notebook will focus on the **Precipitation component**, component, which considers rainfall deficits and dryness persistence. The index calculated using the precipitation component is referred as the Precipitation Drought Index (PDI)." The Precipitation Drought Index (PDI) is a commonly used indicator for assessing drought conditions based on precipitation deficits. It measures the difference between observed precipitation and expected or normal precipitation over a specific time period, typically in relation to the long-term average.

The notebook outlines:

***
1. Loading Python and DE Africa Packages
2. Setting dask cluster
3. Loading area on interest
5. Load CHIRPS data
6. Resampling of data to dekadal (10-day) intervals
7. Calculate the Vegetation Drought Index
8. Export the result as zip

## Getting started

To run this analysis, run all the cells in the notebook, starting with the "Load packages" cell. 

### Load packages

In [1]:
# import calendar
import json
import os
# from datetime import datetime, timedelta

import dask
import geopandas as gpd
import numpy as np
import pandas as pd
import rioxarray
import toolz
import xarray as xr
import datacube
from deafrica_tools.bandindices import calculate_indices
from deafrica_tools.dask import create_local_dask_cluster
from deafrica_tools.datahandling import load_ard
from dekad import group_by_dekad, bin_by_interest_period, get_dekad_no_in_year, get_no_data_mask, max_consecutive_ones
from odc.geo.geobox import GeoBox
from odc.geo.geom import Geometry
from odc.geo.xr import rasterize
from pyarrow import Table
from pyarrow.parquet import write_table

### Connect to the datacube

Connect to the datacube so we can access DE Africa data.
The `app` parameter is a unique name for the analysis which is based on the notebook file name.

In [2]:
# Connect to the datacube
dc = datacube.Datacube(app="PrecipitationDroughtIndex")

### Set up a Dask cluster

Dask can be used to better manage memory use and conduct the analysis in parallel. 
For an introduction to using Dask with Digital Earth Africa, see the [Dask notebook](../../Beginners_guide/08_Parallel_processing_with_dask.ipynb).

>**Note**: We recommend opening the Dask processing window to view the different computations that are being executed; to do this, see the *Dask dashboard in DE Africa* section of the [Dask notebook](../../Beginners_guide/08_Parallel_processing_with_dask.ipynb).

To use Dask, set up the local computing cluster using the cell below.

In [3]:
create_local_dask_cluster()

<Client: 'tcp://127.0.0.1:38811' processes=1 threads=2, memory=11.21 GiB>

### Analysis parameters

The following cell sets important parameters for the analysis:

* `resolution`: The x and y cell resolution of the satellite data in metres (spatial resolution). We'll use 5,000 m, which is approximately equal to the default CHIRPS resolution.
* `output_crs` : The coordinate reference system that the loaded data is to be reprojected to.
* `dask_chunks`:  the size of the dask chunks, dask breaks data into manageable chunks that can be easily stored in memory, e.g. `dict(x=1000,y=1000)`
* `time_range` : Time range to load data for.
* `ip` : The interest period to use to calculate the drought indices e.g. (3, 4, 5 dekads). It defines to what extent past observations are considered. Longer IPs detect more severe drought events. For example, if the IP=3 dekads, then the drought index (say PDI) of 0.35 for dekad 2 of 2006 implies actual drought for dekad 36 of 2005, dekad 1 of 2006 and dekad 2 of 2006.
* `output_dir` :  The directory in which to store results from the analysis.

**If running the notebook for the first time**, keep the default settings below.
This will demonstrate how the analysis works and provide meaningful results.

In [4]:
resolution = (-5000, 5000)
output_crs = "EPSG:6933"
dask_chunks = dict(time=366)
time_range = ("2014","2025")
output_dir = "results"
# Corresponding to the six-months Standardized Precipitation Evapotranspiration Index
ip = 18

# Create the outpur directory if it does not exist.
os.makedirs(output_dir, exist_ok=True)

Below, a vector dataset is called and read which contains the extents of level 1 administrative boundaries in Ethiopia. In the default case, the regional state of Amhara is northern Ethiopia is the area of interest. This can be replaced with any administrative boundary, such as those available on the [GADM database](https://gadm.org/data.html). Larger areas have a larger processing and memory burden and may require additional resources (larger instances) to run effectively.

In [5]:
# Read GADM Ethiopia level 1 file
eth = gpd.read_file('data/gadm41_ETH_1.json')

# Select the country of interest by providing the name below
idx = eth[eth['NAME_1'] == 'Amhara'].index[0]
geopolygon = Geometry(geom=eth.iloc[idx].geometry, crs=eth.crs)

# Create the output path
output_path = os.path.join(output_dir, f"PDI_Amhara.parquet")

## Load CHIRPS data
Load the CHIRPS daily data from the datacube using the analysis parameters set in the previous section.

In [6]:
%%time
ds_rf = dc.load(product='rainfall_chirps_daily',
                measurements=["rainfall"],
                time=time_range,
                dask_chunks=dask_chunks,
                geopolygon=geopolygon,
                output_crs=output_crs,
                resolution=resolution,
               )
                    
ds_rf

CPU times: user 44.7 s, sys: 3.7 s, total: 48.4 s
Wall time: 44.5 s


<xarray.Dataset> Size: 197MB
Dimensions:      (time: 4016, y: 128, x: 96)
Coordinates:
  * time         (time) datetime64[ns] 32kB 2014-01-01T11:59:59.500000 ... 20...
  * y            (y) float64 1kB 1.742e+06 1.738e+06 ... 1.112e+06 1.108e+06
  * x            (x) float64 768B 3.402e+06 3.408e+06 ... 3.872e+06 3.878e+06
    spatial_ref  int32 4B 6933
Data variables:
    rainfall     (time, y, x) float32 197MB dask.array<chunksize=(366, 128, 96), meta=np.ndarray>
Attributes:
    crs:           EPSG:6933
    grid_mapping:  spatial_ref

### Masked the data

In [7]:
# Rasterize the country geopolygon and mask the loaded  rainfall data.
country_mask = rasterize(poly=geopolygon, how=ds_rf.odc.geobox)
ds_rf = ds_rf.where(country_mask)

In [8]:
# Convert to DataArray
da_rf = ds_rf["rainfall"]

# Set -9999 no-data values to NaN
da_rf = da_rf.where(da_rf !=-9999.)

da_rf

<xarray.DataArray 'rainfall' (time: 4016, y: 128, x: 96)> Size: 197MB
dask.array<where, shape=(4016, 128, 96), dtype=float32, chunksize=(366, 128, 96), chunktype=numpy.ndarray>
Coordinates:
  * time         (time) datetime64[ns] 32kB 2014-01-01T11:59:59.500000 ... 20...
  * y            (y) float64 1kB 1.742e+06 1.738e+06 ... 1.112e+06 1.108e+06
  * x            (x) float64 768B 3.402e+06 3.408e+06 ... 3.872e+06 3.878e+06
    spatial_ref  int32 4B 6933
Attributes:
    units:         mm
    nodata:        -9999
    crs:           EPSG:6933
    grid_mapping:  spatial_ref

### Resample data

Resample the rainfall `da_rf` timeseries into **dekadal** (10-day) timesteps.

In [9]:
%%time
# Resample the rainfall data from daily to decadal (10-day) intervals
da_rf_dekadal = group_by_dekad(da_rf).mean(dim="time").compute()
da_rf_dekadal

/opt/venv/lib/python3.12/site-packages/rasterio/warp.py:387: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.
  dest = _reproject(


CPU times: user 28.1 s, sys: 1.85 s, total: 29.9 s
Wall time: 3min 42s


<xarray.DataArray 'rainfall' (dekad: 396, y: 128, x: 96)> Size: 19MB
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
...
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]], dtype=float32)
Coordinates:
  * y            (y) float64 1kB 1.742e+06 1.738e+06 ... 1.112e+06 1.108e+06
  * x            (x) float64 768B 3.402e+06 3.408e+06 ... 3.872e+06 3.878e+06
    spatial_ref  int32 4B 6933
  * dekad        (dekad) datetime64[ns] 3kB 2014-01-01 2014-01-11 ... 2025-04-21
Attributes:
    units:         mm
    nodata:        -9999
    crs:           EPSG:6933
    grid_mapping:  spatial_ref

### Modify the timeseries

The raw timeseries of precipitation is modified to adjust the range of all variables to avoid a division by zero.

In [10]:
da_rf_dekadal_modified =  da_rf_dekadal + 1
da_rf_dekadal_modified

<xarray.DataArray 'rainfall' (dekad: 396, y: 128, x: 96)> Size: 19MB
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
...
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]], dtype=float32)
Coordinates:
  * y            (y) float64 1kB 1.742e+06 1.738e+06 ... 1.112e+06 1.108e+06
  * x            (x) float64 768B 3.402e+06 3.408e+06 ... 3.872e+06 3.878e+06
    spatial_ref  int32 4B 6933
  * dekad        (dekad) datetime64[ns] 3kB 2014-01-01 2014-01-11 ... 2025-04-21

### Group the modified timeseries using the `ip` parameter

The `ip` parameter determines to what extent past observations are considered. Longer IPs detect more severe drought events. The default `ip` used of **18 dekads** corresponds to the 6-month Standardized Precipitation Evapotranspiration Index.

For example, calculating the Precipitation Drought Index for the dekad `2011-01-11` using an interest period of `ip=3` requires rainfall data from the dekad `2010-12-21`, `2011-01-01` and `2011-01-11`.


**Each interest period is labelled using its end dekad.**

In [11]:
# Group the modified rainfall dekadal timeseries by the interest period.
# The dictionary keys are the end dekad for each interest period.
# The values of the dictionary are the rainfall data that belongs to the interest period
da_rf_binned_by_interest_period = bin_by_interest_period(ds=da_rf_dekadal_modified, ip=ip)

In [12]:
# Get the interest periods
interest_periods = list(da_rf_binned_by_interest_period.keys())

### Get the average values for each interest period

Get the actual average rainfall for each interest period.

In [13]:
da_rf_actual_avg_for_ip = xr.concat([da_rf_binned_by_interest_period[i].mean(dim="dekad").assign_coords(dekad=i).expand_dims({"dekad": 1}) for i in interest_periods], dim="dekad")
da_rf_actual_avg_for_ip

<xarray.DataArray 'rainfall' (dekad: 408, y: 128, x: 96)> Size: 20MB
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
...
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]], dtype=float32)
Coordinates:
  * y            (y) float64 1kB 1.742e+06 1.738e+06 ... 1.112e+06 1.108e+06
  * x            (x) float64 768B 3.402e+06 3.408e+06 ... 3.872e+06 3.878e+06
    spatial_ref  int32 4B 6933
  * dekad        (dekad) datetime64[ns] 3kB 2014-01-01 2014-01-11 ... 2025-04-21

### Get the long term average for each interest period over the years of available data


In [14]:
# Group the interest periods by year by getting the dekad number in the year for the end dekad of
# the interest period. 
grouped_by_year = toolz.groupby(lambda dekad: get_dekad_no_in_year(date=dekad), interest_periods)

Get the long term average rainfall for each interest period.

In [15]:
long_term_avg_rf = {}
for dekad_no_in_year, interest_periods_list in grouped_by_year.items():
    long_term_avg_for_period = xr.concat([da_rf_binned_by_interest_period[i] for i in interest_periods_list], dim="dekad").mean(dim="dekad")
    long_term_avg_rf[dekad_no_in_year] = long_term_avg_for_period
    
da_rf_long_term_avg_for_ip = xr.concat([long_term_avg_rf[get_dekad_no_in_year(i)].assign_coords(dekad=i).expand_dims({"dekad": 1}) for  i in interest_periods], dim="dekad")

assert all(da_rf_actual_avg_for_ip.dekad.values == da_rf_long_term_avg_for_ip.dekad.values)

da_rf_long_term_avg_for_ip

<xarray.DataArray 'rainfall' (dekad: 408, y: 128, x: 96)> Size: 20MB
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
...
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]], dtype=float32)
Coordinates:
  * y            (y) float64 1kB 1.742e+06 1.738e+06 ... 1.112e+06 1.108e+06
  * x            (x) float64 768B 3.402e+06 3.408e+06 ... 3.872e+06 3.878e+06
    spatial_ref  int32 4B 6933
  * dekad        (dekad) datetime64[ns] 3kB 2014-01-01 2014-01-11 ... 2025-04-21

### Get the actual length of continous deficit in each interest period

For rainfall the run length is the number of successive dekads in an interest period below the long term average for the same interest period.

In [16]:
%%time
# For each interest period get the maximum number of successive dekads below long term average rainfall in the interest period.
rf_run_length = []
for interest_period in interest_periods:
    # Get the dekads in the interest period
    ds = da_rf_binned_by_interest_period[interest_period]
    
    # Identify pixels which are empty for all dekads
    no_data_mask = xr.apply_ufunc(
        get_no_data_mask,
        ds,
        input_core_dims=[["dekad"]],
        vectorize=True,
        dask="allowed",
    )
    
    # Get the long term average for the interest period
    long_term_avg = da_rf_long_term_avg_for_ip.sel(dekad=interest_period)
    
    # Get the pixels where the rainfall is below the long term average rainfall
    mask = xr.where(ds < long_term_avg, 1, 0)
    
    # Get the maximum number of successive dekads below long term average rainfall.
    actual_run_length = xr.apply_ufunc(
        max_consecutive_ones,
        mask,
        input_core_dims=[["dekad"]],
        vectorize=True,
        dask="allowed",
    )
    
    # Modify the run length
    modified_run_length = (actual_run_length.max() + 1) - actual_run_length
    modified_run_length = modified_run_length.where(~no_data_mask)
    rf_run_length.append(modified_run_length.assign_coords(dekad=interest_period).expand_dims({"dekad": 1}))

da_rf_actual_run_length = xr.concat(rf_run_length, dim="dekad")
da_rf_actual_run_length

CPU times: user 1min 4s, sys: 748 ms, total: 1min 5s
Wall time: 1min 5s


<xarray.DataArray 'rainfall' (dekad: 408, y: 128, x: 96)> Size: 40MB
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
...
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])
Coordinates:
    spatial_ref  int32 4B 6933
  * y            (y) float64 1kB 1.742e+06 1.738e+06 ... 1.112e+06 1.108e+06
  * x            (x) float64 768B 3.402e+06 3.408e+06 ... 3.872e+06 3.878e+06
  * dekad        (dekad) datetime64[ns] 3kB 2014-01-01 2014-01-11 ... 2025-04-21

### Get the long term average of continous deficit in each interest period

In [ ]:
# Get the long term average rainfall run length for each interest period 
long_term_avg_run_lenth_rf = {}
for dekad_no_in_year, interest_periods_list in grouped_by_year.items():
    long_term_avg_for_period = da_rf_actual_run_length.sel(dekad=interest_periods_list).mean(dim="dekad")
    long_term_avg_run_lenth_rf[dekad_no_in_year] = long_term_avg_for_period
    
da_rf_long_term_avg_run_length_for_ip = xr.concat([long_term_avg_run_lenth_rf[get_dekad_no_in_year(i)].assign_coords(dekad=i).expand_dims({"dekad": 1}) for  i in interest_periods], dim="dekad")
da_rf_long_term_avg_run_length_for_ip

### Calculate the scaled Precipitation Drought Index

In [ ]:
PDI = (da_rf_actual_avg_for_ip / da_rf_long_term_avg_for_ip) * np.sqrt((da_rf_actual_run_length / da_rf_long_term_avg_run_length_for_ip))
PDI

In [ ]:
PDI_scaled = (PDI - PDI.min()) / (PDI.max() - PDI.min())
PDI_scaled

In [ ]:
# Convert to DataFrame.
df = PDI_scaled.to_dataframe().drop(columns="spatial_ref")
df

In [ ]:
# Convert the DataFrame to an Arrow table
table = Table.from_pandas(df)

# Get the tables existing metadata
existing_meta = table.schema.metadata

# Dump the crs of the DataArray as new metadata to JSON.
meta_json = json.dumps(dict(crs=str(PDI_scaled.rio.crs)))

# Combine the metadata
combined_meta = {
b"xarray.metadata": meta_json.encode(),
**existing_meta,
}

# Replace the metadata.
table = table.replace_schema_metadata(combined_meta)

### Export the results in a Zip file

In [ ]:
# Write the table
write_table(table, output_path, compression="GZIP")

---

## Additional information

<b> License </b> The code in this notebook is licensed under the [Apache License, Version 2.0](https://www.apache.org/licenses/LICENSE-2.0).

Digital Earth Africa data is licensed under the [Creative Commons by Attribution 4.0](https://creativecommons.org/licenses/by/4.0/) license.

<b> Contact </b> If you need assistance, please post a question on the [DE Africa Slack channel](https://digitalearthafrica.slack.com/) or on the [GIS Stack Exchange](https://gis.stackexchange.com/questions/ask?tags=open-data-cube) using the `open-data-cube` tag (you can view previously asked questions [here](https://gis.stackexchange.com/questions/tagged/open-data-cube)).

If you would like to report an issue with this notebook, you can file one on [Github](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks).

<b> Compatible datacube version </b>

In [ ]:
print(datacube.__version__)

**Last Tested:**

In [ ]:
from datetime import datetime
datetime.today().strftime('%Y-%m-%d')